version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"
  build:
    commands:
      - echo "Build phase complete"
artifacts:
  files:
    - index.html
    - appspec.yml


